theme: jekyll-theme-cayman
title: GiAnMMV's Website
description: My page! [WIP]
classes: wide

collections:
  puzzles:
    output: true
    permalink: /puzzles/:name/

defaults:
  - scope:
      type: "puzzles"
    values:
      layout: "puzzle"
